# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches:
      - master  # default branch

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      
      - name: Using Node 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - run: npm ci
      - run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages  # deploying branch
